### ISSUE TITLE
Support hotkeys

### ISSUE THREAD

**Issue by DasNaCl** [SpeedcubeDE/ocs5#5]
Some users have complained about the need to touch the mouse to call the `timer.reset` function.
So I guess it'd nice to add a functionality to overcome this first world tragedy. i.e:

```
    This.inputUp = function(e) {
        if (This.stackmatActivated)
            return;
        if (This.blockNext) {
            This.blockNext = false;
            e.preventDefault();
            return false;
        }
        if (This.time != 0)
            return;
        if (!This.running)
            This.start();

        if (e.which == 90) // 'z'  <->  90
            This.reset();
    };
```

**Comment by Felk** [comment]
I added the frontend code. You can make this a pull request if you want to contribute this way. Just tell me if you only want me to copy&paste this though

**Comment by DasNaCl** [comment]
Copy & paste is fine, since it's a very minor enhancement.
However, the given code doesn't seem to work, thought. That's probably because of 

```
    $(window).keyup(function(e) {
        if (!This.opened)
            return;
        if (e.which == 32) {   // <-- this
            This.inputUp(e);
        }
    });
```

I totally overlooked that! Sorry, guess moving the if into that lambda should work well then.

```
    $(window).keyup(function(e) {
        if (!This.opened)
            return;
        if (e.which == 32) {
            This.inputUp(e);
        }
        if (e.which == 90) // 'z'  <->  90
            This.reset();
    });
```

**Comment by Felk** [comment]
fixed with https://github.com/Nerogar/ocs5/commit/b2e1374912cd9c4bfac5dfdea601d53fadba5d09
